# Generated by Django 4.0.4 on 2022-05-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='data',
        ),
        migrations.AddField(
            model_name='data',
            name='audio1',
            field=models.IntegerField(default=0, verbose_name='audio1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='audio2',
            field=models.IntegerField(default=0, verbose_name='audio2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='audio3',
            field=models.IntegerField(default=0, verbose_name='audio3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='audio4',
            field=models.IntegerField(default=0, verbose_name='audio4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='duration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='fan',
            field=models.BooleanField(default=False, verbose_name='fan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='hic1',
            field=models.FloatField(default=0, verbose_name='hic1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='hic2',
            field=models.FloatField(default=0, verbose_name='hic2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='hic3',
            field=models.FloatField(default=0, verbose_name='hic3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='hic4',
            field=models.FloatField(default=0, verbose_name='hic4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='hic5',
            field=models.FloatField(default=0, verbose_name='hic5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='hic6',
            field=models.FloatField(default=0, verbose_name='hic6'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='hif1',
            field=models.FloatField(default=0, verbose_name='hif1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='hif2',
            field=models.FloatField(default=0, verbose_name='hif2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='hif3',
            field=models.FloatField(default=0, verbose_name='hif3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='hif4',
            field=models.FloatField(default=0, verbose_name='hif4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='hif5',
            field=models.FloatField(default=0, verbose_name='hif5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='hif6',
            field=models.FloatField(default=0, verbose_name='hif6'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='humidity1',
            field=models.FloatField(default=0, verbose_name='humidity1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='humidity2',
            field=models.FloatField(default=0, verbose_name='humidity2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='humidity3',
            field=models.FloatField(default=0, verbose_name='humidity3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='humidity4',
            field=models.FloatField(default=0, verbose_name='humidity4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='humidity5',
            field=models.FloatField(default=0, verbose_name='humidity5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='humidity6',
            field=models.FloatField(default=0, verbose_name='humidity6'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='motion1',
            field=models.IntegerField(default=0, verbose_name='motion1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='motion2',
            field=models.IntegerField(default=0, verbose_name='motion2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='motion3',
            field=models.IntegerField(default=0, verbose_name='motion3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='motion4',
            field=models.IntegerField(default=0, verbose_name='motion4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='period',
            field=models.IntegerField(default=0, verbose_name='period'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='tempc1',
            field=models.FloatField(default=0, verbose_name='tempc1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='tempc2',
            field=models.FloatField(default=0, verbose_name='tempc2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='tempc3',
            field=models.FloatField(default=0, verbose_name='tempc3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='tempc4',
            field=models.FloatField(default=0, verbose_name='tempc4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='tempc5',
            field=models.FloatField(default=0, verbose_name='tempc5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='tempc6',
            field=models.FloatField(default=0, verbose_name='tempc6'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='tempf1',
            field=models.FloatField(default=0, verbose_name='tempf1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='tempf2',
            field=models.FloatField(default=0, verbose_name='tempf2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='tempf3',
            field=models.FloatField(default=0, verbose_name='tempf3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='tempf4',
            field=models.FloatField(default=0, verbose_name='tempf4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='tempf5',
            field=models.FloatField(default=0, verbose_name='tempf5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='tempf6',
            field=models.FloatField(default=0, verbose_name='tempf6'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fan',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='duration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fan',
            name='period',
            field=models.IntegerField(default=0, verbose_name='period'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Temperature',
        ),
    ]
