# Generated by Django 4.0.4 on 2022-05-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_remove_data_data_data_audio1_data_audio2_data_audio3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='fan',
            field=models.IntegerField(verbose_name='fan'),
        ),
        migrations.AlterField(
            model_name='data',
            name='pub_date',
            field=models.DateTimeField(verbose_name='pub_date'),
        ),
    ]
