# Generated by Django 4.0.4 on 2022-05-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_data_fan_alter_data_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='pub_date'),
        ),
    ]
