# Generated by Django 4.0.4 on 2022-05-29 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_alter_data_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='hic1',
        ),
        migrations.RemoveField(
            model_name='data',
            name='hic2',
        ),
        migrations.RemoveField(
            model_name='data',
            name='hic3',
        ),
        migrations.RemoveField(
            model_name='data',
            name='hic4',
        ),
        migrations.RemoveField(
            model_name='data',
            name='hic5',
        ),
        migrations.RemoveField(
            model_name='data',
            name='hic6',
        ),
        migrations.RemoveField(
            model_name='data',
            name='hif1',
        ),
        migrations.RemoveField(
            model_name='data',
            name='hif2',
        ),
        migrations.RemoveField(
            model_name='data',
            name='hif3',
        ),
        migrations.RemoveField(
            model_name='data',
            name='hif4',
        ),
        migrations.RemoveField(
            model_name='data',
            name='hif5',
        ),
        migrations.RemoveField(
            model_name='data',
            name='hif6',
        ),
        migrations.RemoveField(
            model_name='data',
            name='tempf1',
        ),
        migrations.RemoveField(
            model_name='data',
            name='tempf2',
        ),
        migrations.RemoveField(
            model_name='data',
            name='tempf3',
        ),
        migrations.RemoveField(
            model_name='data',
            name='tempf4',
        ),
        migrations.RemoveField(
            model_name='data',
            name='tempf5',
        ),
        migrations.RemoveField(
            model_name='data',
            name='tempf6',
        ),
    ]
