# Generated by Django 4.0.5 on 2022-06-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_remove_data_hic1_remove_data_hic2_remove_data_hic3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='motion1',
        ),
        migrations.RemoveField(
            model_name='data',
            name='motion2',
        ),
        migrations.RemoveField(
            model_name='data',
            name='motion3',
        ),
        migrations.RemoveField(
            model_name='data',
            name='motion4',
        ),
        migrations.AddField(
            model_name='data',
            name='humidity7',
            field=models.FloatField(default=0, verbose_name='humidity7'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='humidity8',
            field=models.FloatField(default=0, verbose_name='humidity8'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='tempc7',
            field=models.FloatField(default=0, verbose_name='tempc7'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='tempc8',
            field=models.FloatField(default=0, verbose_name='tempc8'),
            preserve_default=False,
        ),
    ]
